FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:65a240ad8bd3f2fff3e18a22ebadc40da0b145616231fc1e16251f3c6dee087a

COPY . /usr/local/src/exodus-lambda

RUN \
    microdnf -y install shadow-utils python39 /usr/bin/openssl /usr/bin/envsubst \
    && cd /usr/local/src/exodus-lambda \
    && pip3 install --require-hashes -r requirements-fakefront.txt \
    && pip3 install --editable . \
    && microdnf clean all && rm -rf /var/cache/yum

RUN adduser fakefront
USER fakefront

EXPOSE 8080

WORKDIR /usr/local/src/exodus-lambda

ENTRYPOINT ["gunicorn", "-b", ":8080", "support.fakefront"]
