FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:c9c8f91b030f13c44b195b728a0c43c29946b4a9094b2ee62ebaf9c9ee540bcc

COPY . /usr/local/src/exodus-lambda

RUN \
    microdnf -y install shadow-utils python39 /usr/bin/openssl /usr/bin/envsubst \
    && cd /usr/local/src/exodus-lambda \
    && pip3 install --require-hashes -r requirements-fakefront.txt \
    && pip3 install --editable . \
    && microdnf clean all && rm -rf /var/cache/yum

RUN adduser fakefront
USER fakefront

EXPOSE 8080

WORKDIR /usr/local/src/exodus-lambda

ENTRYPOINT ["gunicorn", "-b", ":8080", "support.fakefront"]
