FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:cc2925acdbac0b199a3e51b51e7005b14a902addbcc238f12fd999947c2584da

COPY . /usr/local/src/exodus-lambda

RUN \
    microdnf -y install shadow-utils python39 /usr/bin/openssl /usr/bin/envsubst \
    && cd /usr/local/src/exodus-lambda \
    && pip3 install --require-hashes -r requirements-fakefront.txt \
    && pip3 install --editable . \
    && microdnf clean all && rm -rf /var/cache/yum

RUN adduser fakefront
USER fakefront

EXPOSE 8080

WORKDIR /usr/local/src/exodus-lambda

ENTRYPOINT ["gunicorn", "support.fakefront"]
