AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Configuration for exodus-cdn Lambda@Edge deployment

Parameters:
  env:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev
    Description: The environment for which resources are intended
  oai:
    Type: String
    Description: The origin access identity ID associated with the environment
  project:
    Type: String
    Default: exodus
    Description: The project name under which resources are created
  lambdafunctionrole:
    Type: String
    Default: None
    Description: The IAM Role ARN for Lambda Function resource

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub ${project}-cdn-${env}
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers:
              - Want-Digest
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref OriginRequestFunc.Version
            - EventType: origin-response
              LambdaFunctionARN: !Ref OriginResponseFunc.Version
          TargetOriginId: !Sub S3-${project}-cdn-${env}
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Sub "${project}-cdn-${env}.s3.amazonaws.com"
            Id: !Sub "S3-${project}-cdn-${env}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${oai}"

  OriginRequestFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${project}-origin-request-${env}
      CodeUri:
      Handler: exodus_lambda.origin_request
      Role: !Sub ${lambdafunctionrole}
      Runtime: python3.7
      Timeout: 5
      AutoPublishAlias: live

  OriginResponseFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${project}-origin-response-${env}
      CodeUri:
      Handler: exodus_lambda.origin_response
      Role: !Sub ${lambdafunctionrole}
      Runtime: python3.7
      Timeout: 5
      AutoPublishAlias: live

  OriginRequestAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${project}-origin-request-alarm-${env}
      AlarmDescription: !Sub ${project}-origin-request-${env} invocation errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref OriginRequestFunc
      Statistic: Sum
      Period: 180
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 3

  OriginResponseAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${project}-origin-response-alarm-${env}
      AlarmDescription: !Sub ${project}-origin-response-${env} invocation errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref OriginResponseFunc
      Statistic: Sum
      Period: 180
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 3

Outputs:
  Distribution:
    Description: distribution domain name
    Value: !GetAtt Distribution.DomainName

  OriginRequestFunc:
    Description: origin-request function ARN with version
    Value: !Ref OriginRequestFunc.Version

  OriginResponseFunc:
    Description: origin-response function ARN with version
    Value: !Ref OriginResponseFunc.Version

  OriginRequestAlarm:
    Description: origin-request function alarm ARN
    Value: !GetAtt OriginRequestAlarm.Arn

  OriginResponseAlarm:
    Description: origin-response function alarm ARN
    Value: !GetAtt OriginResponseAlarm.Arn
